### ISSUE TITLE
get Error when work on 4 or 5 Sentence 

### ISSUE THREAD

**Issue by mzolfaghari71** [Text-Mining/Persian-NER#5] opened 2018-11-30 09:50 UTC
I start work with correction sentence and got this Error 
Error.
An error occurred while processing your request
on that time my url was :
http://app.text-mining.ir/CustomerPanel/NER/Tag/2841f78a-84f4-e811-bf64-b01b0c4ef2e3

**Comment by Hameds** [comment] 2018-11-30 09:54
Thanks for reporting this bug. We will investigate it. It may be related to temporary maintenance outage caused by new deployment

**Comment by Hameds** [comment] 2018-12-01 09:09
Ok. It's confirmed bug and we are working on this. Should be fixed in a couple of hours

**Comment by Hameds** [comment] 2018-12-01 16:52
looking into logs, we discovered the origin of this bug and we fixed it. but because this is 500 (server error) default page you may face this error in the future for a different reason (like low server resources). That would be another issue but for now we are pretty sure that this bug is fixed :)

**Closed by Hameds** 2018-12-01 16:52 UTC
Labels: bug
